server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://PRODUCT-MS
          predicates:
            - Path=/api/v1/products/**
        - id: order-service
          uri: lb://ORDER-MS
          predicates:
            - Path=/api/v1/orders/**
        - id: inventory-service
          uri: lb://INVENTORY-MS
          predicates:
            - Path=/api/v1/inventory/**